#!/usr/bin/python3
import math

def factors(filename):
    with open(filename, 'r') as f:
        for line in f:
            n = int(line.strip())
            for i in range(2, int(math.sqrt(n)) + 1):
                if n % i == 0:
                    print(f'{n}={i}*{n//i}')
                    break
            else:
                print(f'{n} is prime')

factors('tests/test00')
